version: "3.6"
networks:
  workshop:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
services:
  db:
    image: juansehgu/dbmaria:latest
    container_name: db
    ports:
      - "3306:3306"
    networks:
      workshop:
        ipv4_address: 172.30.0.2
  jerseyms:
    container_name: jersey
    image: juansehgu/jersey:latest
    environment:
      SERVER_IP: "172.30.0.3"
      DB_IP: "172.30.0.2"
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      workshop:
        ipv4_address: 172.30.0.3
